[tool.poetry]
name = "mongo-c-driver-dev"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.9"
dagon = "^0.9.3"
aiohttp = "^3.8.1"

[tool.poetry.dev-dependencies]
yapf = "^0.32.0"
toml = "^0.10.2"

